import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className="flex min-h-screen flex-col px-44 py-12 text-slate-700"
        // style={{
        //   backgroundColor: "#ffffff",
        //   background:
        //     "radial-gradient(circle, transparent 20%, #ffffff 20%, #ffffff 80%, transparent 80%, transparent), radial-gradient(circle, transparent 20%, #ffffff 20%, #ffffff 80%, transparent 80%, transparent) 10px 10px, linear-gradient(#e5e7eb 0.8px, transparent 0.8px) 0 -0.4px, linear-gradient(90deg, #e5e7eb 0.8px, #ffffff 0.8px) -0.4px 0;",
        //   backgroundSize: "20px 20px, 20px 20px, 10px 10px, 10px 10px;",
        // }}
      >
        <article className="">
          <header className="flex items-center justify-between py-4">
            <h1 className="text-xl font-bold">
              Map<span className="text-cyan-400">It!</span>
            </h1>
            <nav className="space-x-4 text-sm font-medium">
              <button className="px-4 hover:text-cyan-400">Sign Up</button>
              <button>Log In</button>
            </nav>
          </header>
          <section className="space-y-8 px-44 py-20 text-center text-slate-800">
            <div className=" text-[5rem] font-semibold leading-tight">
              Easily publish and share{" "}
              <span className="text-indigo-500">beautiful</span> maps online.
            </div>
            <h2 className="text-xl font-medium text-slate-500">
              Spatial data has never looked so good.
            </h2>
            <section className="space-x-8 font-medium">
              <Link
                href="/map"
                className=" rounded-md py-3 text-center text-slate-800 underline underline-offset-8"
              >
                Create a map{" "}
                <span className="font-semibold text-cyan-400">+</span>
              </Link>
              <button className=" rounded-md py-3 text-center text-slate-800 underline underline-offset-8">
                View Examples{" "}
                <span className="font-semibold text-indigo-500">&#x2192;</span>
              </button>
            </section>
          </section>
        </article>
      </main>
    </>
  );
}
